backend:
  name: github
  repo: jeualvarez/RT # Path to your Github repository
  branch: master # Branch to update

media_folder: "src/assets/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/assets/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "categories" # Used in routes, e.g. /admin/collections/faqs
    label: "Categories" # Used in the UI
    folder: "gulp/common/faqs/categories" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template i.e. title.md
    extension: "json"
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "order", widget: "number", default: 3, min: 1, max: 100, valueType: "int"}

  - name: "questions"
    label: "Questions"
    folder: "gulp/common/faqs"
    create: true
    slug: "{{slug}}"
    extension: "json"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Category", name: "parent", widget: "relation", collection: "categories", searchFields: ["title"], valueField: "title"}
